"use client";

import { useEffect, useMemo, useState } from "react";

type Post = { id:number; titulo:string; resumo:string; categoria:string; data:string; imagem:string; destaque?:boolean; tempo:string; conteudo:string };

const posts: Post[] = [
  {id:1,titulo:"Como a inteligência artificial está redesenhando o futuro do trabalho",resumo:"Novas ferramentas ampliam capacidades humanas e transformam a rotina de empresas brasileiras.",categoria:"Tecnologia",data:"12 ago 2026 · 09:30",tempo:"8 min",destaque:true,imagem:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85",conteudo:"A inteligência artificial deixou de ser uma promessa distante. Hoje, ela já participa da rotina de profissionais de diferentes áreas, apoiando decisões, automatizando tarefas repetitivas e abrindo espaço para trabalhos mais criativos.\n\nA mudança mais importante não está apenas nas ferramentas, mas na forma como pessoas e organizações passam a pensar seus processos. Equipes que aprendem a combinar conhecimento humano com tecnologia ganham agilidade sem perder a sensibilidade necessária para resolver problemas complexos.\n\nNo Brasil, esse movimento cresce em empresas de todos os portes. O desafio agora é garantir formação contínua, transparência e uso responsável para que os ganhos sejam compartilhados."},
  {id:2,titulo:"Cidades mais humanas começam por ruas pensadas para pessoas",resumo:"Urbanismo, mobilidade e áreas verdes se encontram em projetos que devolvem qualidade de vida.",categoria:"Cidades",data:"11 ago 2026 · 16:15",tempo:"6 min",destaque:true,imagem:"https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=1400&q=85",conteudo:"Uma cidade acolhedora é aquela em que caminhar, encontrar pessoas e acessar serviços essenciais faz parte de uma experiência simples e segura.\n\nProjetos recentes mostram que pequenas intervenções — uma calçada mais larga, uma praça sombreada ou uma ciclovia conectada — podem transformar bairros inteiros. O segredo está em ouvir quem vive o território todos os dias."},
  {id:3,titulo:"Energia limpa avança e cria novas oportunidades no Nordeste",resumo:"Investimentos em fontes renováveis movimentam a economia e fortalecem comunidades locais.",categoria:"Sustentabilidade",data:"10 ago 2026 · 11:40",tempo:"7 min",destaque:true,imagem:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1400&q=85",conteudo:"O sol e o vento tornaram o Nordeste protagonista de uma transformação energética. Além de reduzir emissões, os novos projetos criam empregos e impulsionam cadeias produtivas locais.\n\nPara que o desenvolvimento seja duradouro, especialistas defendem planejamento territorial e participação ativa das comunidades em todas as etapas."},
  {id:4,titulo:"Educação digital vai além da tela e aproxima comunidades",resumo:"Iniciativas locais usam tecnologia para ampliar repertórios e criar novas oportunidades.",categoria:"Educação",data:"09 ago 2026 · 14:20",tempo:"5 min",imagem:"https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=85",conteudo:"A tecnologia ganha sentido quando aproxima pessoas e resolve necessidades reais. Em escolas e centros comunitários, projetos de educação digital estão ajudando estudantes a transformar curiosidade em conhecimento aplicado."},
  {id:5,titulo:"Economia criativa transforma ideias em negócios de impacto",resumo:"Cultura, design e inovação formam uma rede produtiva que cresce em todo o país.",categoria:"Negócios",data:"08 ago 2026 · 10:05",tempo:"9 min",imagem:"https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=85",conteudo:"Criadores brasileiros estão descobrindo novas formas de unir propósito, identidade e sustentabilidade financeira. Essa economia se apoia em colaboração e na força das redes locais."},
  {id:6,titulo:"Saúde preventiva ganha força com hábitos possíveis",resumo:"Pequenas mudanças consistentes ajudam a construir uma rotina com mais equilíbrio.",categoria:"Bem-estar",data:"07 ago 2026 · 08:45",tempo:"4 min",imagem:"https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=85",conteudo:"Cuidar da saúde não precisa significar mudanças radicais. Sono regular, movimento diário e alimentação equilibrada formam uma base acessível para viver melhor."},
];
const categorias=["Todas","Tecnologia","Cidades","Sustentabilidade","Educação","Negócios","Bem-estar"];

export default function Home(){
 const [dark,setDark]=useState(false),[busca,setBusca]=useState(false),[termo,setTermo]=useState(""),[categoria,setCategoria]=useState("Todas"),[slide,setSlide]=useState(0),[pagina,setPagina]=useState<"home"|"artigo"|"admin">("home"),[artigo,setArtigo]=useState<Post|null>(null),[menu,setMenu]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{const t=setInterval(()=>setSlide(s=>(s+1)%3),5500);return()=>clearInterval(t)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light"},[dark]);
 const filtrados=useMemo(()=>posts.filter(p=>(categoria==="Todas"||p.categoria===categoria)&&(`${p.titulo} ${p.resumo} ${p.categoria} ${p.conteudo}`.toLowerCase().includes(termo.toLowerCase()))),[categoria,termo]);
 function abrir(p:Post){sessionStorage.setItem("moveon-scroll",String(scrollY));setArtigo(p);setPagina("artigo");scrollTo(0,0)}
 function voltar(){setPagina("home");setTimeout(()=>scrollTo(0,Number(sessionStorage.getItem("moveon-scroll")||0)),20)}
 function compartilhar(rede:string){const url=encodeURIComponent(location.href); const links:Record<string,string>={WhatsApp:`https://wa.me/?text=${encodeURIComponent(artigo?.titulo||"")}%20${url}`,LinkedIn:`https://www.linkedin.com/sharing/share-offsite/?url=${url}`,Facebook:`https://www.facebook.com/sharer/sharer.php?u=${url}`}; if(links[rede])window.open(links[rede],"_blank");else navigator.clipboard.writeText(location.href);setToast(rede==="Link"?"Link copiado!":"Compartilhamento aberto!");setTimeout(()=>setToast(""),2200)}
 return <main className="site-shell">
  <header className="cabecalho"><button className="marca" onClick={()=>{setPagina("home");setCategoria("Todas")}} aria-label="Ir para o início"><img src="/logo.png" alt="MOVE.ON"/></button><nav className={menu?"nav aberta":"nav"}><button onClick={()=>setPagina("home")}>Início</button><button onClick={()=>{setPagina("home");setTimeout(()=>document.querySelector("#publicacoes")?.scrollIntoView(),20)}}>Publicações</button><button onClick={()=>setCategoria("Tecnologia")}>Tecnologia</button><button onClick={()=>setPagina("admin")}>Administração</button></nav><div className="acoes"><button className="icon-btn" onClick={()=>setBusca(!busca)} aria-label="Abrir busca">⌕</button><button className="theme" onClick={()=>setDark(!dark)} aria-label="Alternar tema"><span>{dark?"☾":"☀"}</span></button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button></div></header>
  <div className={busca?"busca aberta":"busca"}><label htmlFor="q">O que você procura?</label><div><input id="q" autoFocus={busca} value={termo} onChange={e=>setTermo(e.target.value)} placeholder="Busque por título, assunto ou categoria…"/><button onClick={()=>{setPagina("home");setBusca(false)}}>Buscar</button></div></div>
  {pagina==="home"&&<>
   <section className="hero"><div className="hero-img" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.82),rgba(0,0,0,.1)),url(${posts[slide].imagem})`}}/><div className="hero-content"><span className="chapeu">EM DESTAQUE</span><h1>{posts[slide].titulo}</h1><p>{posts[slide].resumo}</p><button className="primario" onClick={()=>abrir(posts[slide])}>Ler publicação <b>→</b></button></div><div className="dots">{[0,1,2].map(i=><button key={i} className={i===slide?"ativo":""} onClick={()=>setSlide(i)} aria-label={`Destaque ${i+1}`}/>)}</div></section>
   <section className="conteudo" id="publicacoes"><div className="titulo-secao"><div><span className="eyebrow">CONTEÚDO QUE MOVE</span><h2>Publicações recentes</h2></div><p>Informação clara para acompanhar um mundo em movimento.</p></div>
    <div className="categorias">{categorias.map(c=><button key={c} className={categoria===c?"ativa":""} onClick={()=>setCategoria(c)}>{c}</button>)}</div>
    <div className="grid-posts">{filtrados.map(p=><article className="post-card" key={p.id} onClick={()=>abrir(p)} tabIndex={0}><div className="card-img"><img src={p.imagem} alt=""/><button onClick={e=>{e.stopPropagation();setCategoria(p.categoria)}}>{p.categoria}</button></div><div className="card-body"><div className="meta"><span>{p.data}</span><span>{p.tempo} de leitura</span></div><h3>{p.titulo}</h3><p>{p.resumo}</p><span className="leia">Leia agora <b>↗</b></span></div></article>)}</div>
    {filtrados.length===0&&<div className="vazio"><b>Nenhuma publicação encontrada.</b><p>Tente buscar por outro termo ou categoria.</p></div>}
    <button className="carregar">Carregar mais publicações <span>↓</span></button>
   </section>
   <section className="newsletter"><span>FIQUE POR DENTRO</span><h2>Conteúdo que chega até você.</h2><p>Uma seleção do que realmente importa, direto no seu e-mail.</p><form onSubmit={e=>{e.preventDefault();setToast("Inscrição realizada!")}}><input aria-label="Seu melhor e-mail" placeholder="Seu melhor e-mail" type="email" required/><button>Quero receber</button></form></section>
  </>}
  {pagina==="artigo"&&artigo&&<article className="artigo"><button className="voltar" onClick={voltar}>← Voltar às publicações</button><header><button className="tag" onClick={()=>{setCategoria(artigo.categoria);voltar()}}>{artigo.categoria}</button><h1>{artigo.titulo}</h1><p>{artigo.resumo}</p><div className="artigo-meta"><span>◷ {artigo.data} — horário de Brasília</span><span>◉ {artigo.tempo} de leitura</span></div></header><img className="capa-artigo" src={artigo.imagem} alt="Imagem de capa da publicação"/><div className="artigo-layout"><aside><b>Compartilhe</b><button onClick={()=>compartilhar("WhatsApp")}>W</button><button onClick={()=>compartilhar("LinkedIn")}>in</button><button onClick={()=>compartilhar("Facebook")}>f</button><button onClick={()=>compartilhar("Link")}>↗</button></aside><div className="texto">{artigo.conteudo.split("\n\n").map((p,i)=>i===1?<blockquote key={i}>{p}</blockquote>:<p key={i}>{p}</p>)}<h2>O próximo passo começa agora</h2><p>Mais do que acompanhar tendências, é preciso compreender o que elas significam para a vida real. Informação de qualidade ajuda a escolher caminhos com mais consciência.</p></div></div></article>}
  {pagina==="admin"&&<Dashboard onSair={()=>setPagina("home")} setToast={setToast}/>} 
  <footer><img src="/logo.png" alt="MOVE.ON"/><p>Conteúdo para quem não para de evoluir.</p><div><button>Sobre</button><button>Contato</button><button>Privacidade</button></div><small>© 2026 MOVE.ON. Todos os direitos reservados.</small></footer>{toast&&<div className="toast">✓ {toast}</div>}
 </main>
}

function Dashboard({onSair,setToast}:{onSair:()=>void,setToast:(v:string)=>void}){const [aba,setAba]=useState("Visão geral");const itens=["Visão geral","Publicações","Nova publicação","Categorias","Métricas","Aparência","Administrador"];return <div className="admin"><aside className="admin-side"><img src="/logo.png" alt="MOVE.ON"/><span>PAINEL ADMINISTRATIVO</span>{itens.map(i=><button key={i} className={aba===i?"ativo":""} onClick={()=>setAba(i)}><b>{i==="Visão geral"?"⌂":i==="Métricas"?"↗":"□"}</b>{i}</button>)}<button className="site" onClick={onSair}>← Ver o portal</button></aside><section className="admin-main"><div className="admin-top"><div><span>PAINEL ADMINISTRATIVO</span><h1>{aba}</h1></div><div className="avatar">AM</div></div>{aba==="Visão geral"&&<><div className="metricas"><Metric n="12.840" label="Acessos este mês" delta="+18%"/><Metric n="4.620" label="Leitores únicos" delta="+12%"/><Metric n="68%" label="Engajamento" delta="+6%"/><Metric n="42" label="Publicações" delta="+4"/></div><div className="painel-grid"><div className="chart"><div className="painel-titulo"><div><span>DESEMPENHO</span><h2>Acessos nos últimos 7 dias</h2></div><b>8.942 acessos</b></div><div className="barras">{[45,67,58,81,72,93,76].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][i]}</small></div>)}</div></div><div className="rapido"><span>ACESSO RÁPIDO</span><h2>O que deseja fazer?</h2><button onClick={()=>setAba("Nova publicação")}>＋ <span><b>Nova publicação</b><small>Crie e publique conteúdo</small></span></button><button onClick={()=>setAba("Categorias")}>▤ <span><b>Gerenciar categorias</b><small>Organize seu conteúdo</small></span></button><button onClick={()=>setAba("Aparência")}>◐ <span><b>Ajustar aparência</b><small>Logo, nome e favicon</small></span></button></div></div><div className="tabela"><div className="painel-titulo"><div><span>CONTEÚDO</span><h2>Publicações recentes</h2></div><button onClick={()=>setAba("Publicações")}>Ver todas →</button></div>{posts.slice(0,4).map((p,i)=><div className="linha" key={p.id}><img src={p.imagem} alt=""/><div><b>{p.titulo}</b><span>{p.categoria} · {p.data}</span></div><em className={i===2?"rascunho":"publicado"}>{i===2?"Rascunho":"Publicado"}</em><strong>{["2.481","1.920","—","1.574"][i]} <small>acessos</small></strong><button>•••</button></div>)}</div></>}{aba==="Nova publicação"&&<Editor setToast={setToast}/>} {!["Visão geral","Nova publicação"].includes(aba)&&<PaginaAdmin titulo={aba} setToast={setToast}/>}</section></div>}
function Metric({n,label,delta}:{n:string,label:string,delta:string}){return <div className="metric"><span>↗</span><b>{n}</b><p>{label}</p><small>{delta} no período</small></div>}
function Editor({setToast}:{setToast:(v:string)=>void}){return <div className="editor"><div className="form-card"><label>Título da publicação<input placeholder="Digite um título claro e atrativo"/></label><div className="form-row"><label>Categoria<select><option>Selecione uma categoria</option>{categorias.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select><option>Rascunho</option><option>Publicar agora</option><option>Agendado</option></select></label></div><label>Resumo<textarea placeholder="Escreva uma breve introdução…" rows={3}/></label><label>Conteúdo</label><div className="toolbar"><button>H1</button><button><b>B</b></button><button><i>I</i></button><button>☷</button><button>“ ”</button><button>&lt;/&gt;</button><button>Imagem</button><button>Vídeo</button></div><div className="content-edit" contentEditable suppressContentEditableWarning>Comece a escrever sua publicação aqui…</div><div className="upload"><b>＋ Adicionar imagens de capa</b><span>JPG, PNG ou WebP · máximo 5 MB cada</span></div><label>Programar publicação<input type="datetime-local"/></label></div><div className="editor-actions"><button>Visualizar</button><button onClick={()=>setToast("Rascunho salvo com segurança!")}>Salvar rascunho</button><button className="primario" onClick={()=>setToast("Publicação programada!")}>Publicar</button></div></div>}
function PaginaAdmin({titulo,setToast}:{titulo:string,setToast:(v:string)=>void}){return <div className="placeholder-admin"><div><span>GESTÃO</span><h2>{titulo}</h2><p>{titulo==="Métricas"?"Dados reais de acesso e engajamento, sem tráfego administrativo ou robôs conhecidos.":"Gerencie esta área do portal com segurança e facilidade."}</p></div><button className="primario" onClick={()=>setToast("Alterações salvas!")}>{titulo==="Publicações"?"＋ Nova publicação":"Salvar alterações"}</button><div className="config-card"><h3>{titulo}</h3><p>Os controles desta seção estão prontos para integração com o banco PostgreSQL e validação segura no servidor.</p><label>Nome ou descrição<input defaultValue={titulo==="Aparência"?"MOVE.ON":""} placeholder="Digite aqui"/></label><label>Configuração<textarea rows={5} placeholder="Adicione informações…"/></label></div></div>}
