"use client";

import { useEffect, useMemo, useState } from "react";
import { LayoutDashboard, FileText, SquarePen, Tags, ChartNoAxesCombined, Palette, UserCog, ExternalLink, Eye, TrendingUp, Users, MousePointerClick, Plus, Image as ImageIcon, Video, Code2, Bold, Italic, List, Quote, Save, CalendarClock, Settings, Trash2, Pencil, Search, ChevronRight } from "lucide-react";

type Post = { id:number; titulo:string; resumo:string; categoria:string; data:string; imagem:string; destaque?:boolean; tempo:string; conteudo:string };

const posts: Post[] = [
  {id:1,titulo:"Como a inteligência artificial está redesenhando o futuro do trabalho",resumo:"Novas ferramentas ampliam capacidades humanas e transformam a rotina de empresas brasileiras.",categoria:"Tecnologia",data:"12 ago 2026 · 09:30",tempo:"8 min",destaque:true,imagem:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85",conteudo:"A inteligência artificial deixou de ser uma promessa distante. Hoje, ela já participa da rotina de profissionais de diferentes áreas, apoiando decisões, automatizando tarefas repetitivas e abrindo espaço para trabalhos mais criativos.\n\nA mudança mais importante não está apenas nas ferramentas, mas na forma como pessoas e organizações passam a pensar seus processos. Equipes que aprendem a combinar conhecimento humano com tecnologia ganham agilidade sem perder a sensibilidade necessária para resolver problemas complexos.\n\nNo Brasil, esse movimento cresce em empresas de todos os portes. O desafio agora é garantir formação contínua, transparência e uso responsável para que os ganhos sejam compartilhados."},
  {id:2,titulo:"Cidades mais humanas começam por ruas pensadas para pessoas",resumo:"Urbanismo, mobilidade e áreas verdes se encontram em projetos que devolvem qualidade de vida.",categoria:"Cidades",data:"11 ago 2026 · 16:15",tempo:"6 min",destaque:true,imagem:"https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=1400&q=85",conteudo:"Uma cidade acolhedora é aquela em que caminhar, encontrar pessoas e acessar serviços essenciais faz parte de uma experiência simples e segura.\n\nProjetos recentes mostram que pequenas intervenções — uma calçada mais larga, uma praça sombreada ou uma ciclovia conectada — podem transformar bairros inteiros. O segredo está em ouvir quem vive o território todos os dias."},
  {id:3,titulo:"Energia limpa avança e cria novas oportunidades no Nordeste",resumo:"Investimentos em fontes renováveis movimentam a economia e fortalecem comunidades locais.",categoria:"Sustentabilidade",data:"10 ago 2026 · 11:40",tempo:"7 min",destaque:true,imagem:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1400&q=85",conteudo:"O sol e o vento tornaram o Nordeste protagonista de uma transformação energética. Além de reduzir emissões, os novos projetos criam empregos e impulsionam cadeias produtivas locais.\n\nPara que o desenvolvimento seja duradouro, especialistas defendem planejamento territorial e participação ativa das comunidades em todas as etapas."},
  {id:4,titulo:"Educação digital vai além da tela e aproxima comunidades",resumo:"Iniciativas locais usam tecnologia para ampliar repertórios e criar novas oportunidades.",categoria:"Educação",data:"09 ago 2026 · 14:20",tempo:"5 min",imagem:"https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=85",conteudo:"A tecnologia ganha sentido quando aproxima pessoas e resolve necessidades reais. Em escolas e centros comunitários, projetos de educação digital estão ajudando estudantes a transformar curiosidade em conhecimento aplicado."},
  {id:5,titulo:"Economia criativa transforma ideias em negócios de impacto",resumo:"Cultura, design e inovação formam uma rede produtiva que cresce em todo o país.",categoria:"Negócios",data:"08 ago 2026 · 10:05",tempo:"9 min",imagem:"https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=85",conteudo:"Criadores brasileiros estão descobrindo novas formas de unir propósito, identidade e sustentabilidade financeira. Essa economia se apoia em colaboração e na força das redes locais."},
  {id:6,titulo:"Saúde preventiva ganha força com hábitos possíveis",resumo:"Pequenas mudanças consistentes ajudam a construir uma rotina com mais equilíbrio.",categoria:"Bem-estar",data:"07 ago 2026 · 08:45",tempo:"4 min",imagem:"https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=85",conteudo:"Cuidar da saúde não precisa significar mudanças radicais. Sono regular, movimento diário e alimentação equilibrada formam uma base acessível para viver melhor."},
];
const categorias=["Todas","Tecnologia","Cidades","Sustentabilidade","Educação","Negócios","Bem-estar"];
const categoriasExtras:Record<number,string[]>={1:["Negócios"],2:["Sustentabilidade"],3:["Negócios"],4:["Tecnologia"],5:["Cidades"],6:["Educação"]};
const categoriasDoPost=(p:Post)=>[p.categoria,...(categoriasExtras[p.id]||[])];

export default function Home(){
 const [dark,setDark]=useState(false),[busca,setBusca]=useState(false),[termo,setTermo]=useState(""),[categoria,setCategoria]=useState("Todas"),[slide,setSlide]=useState(0),[pagina,setPagina]=useState<"home"|"artigo"|"admin">("home"),[artigo,setArtigo]=useState<Post|null>(null),[menu,setMenu]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{const t=setInterval(()=>setSlide(s=>(s+1)%3),5500);return()=>clearInterval(t)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light"},[dark]);
 const filtrados=useMemo(()=>posts.filter(p=>(categoria==="Todas"||categoriasDoPost(p).includes(categoria))&&(`${p.titulo} ${p.resumo} ${categoriasDoPost(p).join(" ")} ${p.conteudo}`.toLowerCase().includes(termo.toLowerCase()))),[categoria,termo]);
 function abrir(p:Post){sessionStorage.setItem("moveon-scroll",String(scrollY));setArtigo(p);setPagina("artigo");scrollTo(0,0)}
 function voltar(){setPagina("home");setTimeout(()=>scrollTo(0,Number(sessionStorage.getItem("moveon-scroll")||0)),20)}
 function compartilhar(rede:string){const url=encodeURIComponent(location.href); const links:Record<string,string>={WhatsApp:`https://wa.me/?text=${encodeURIComponent(artigo?.titulo||"")}%20${url}`,LinkedIn:`https://www.linkedin.com/sharing/share-offsite/?url=${url}`,Facebook:`https://www.facebook.com/sharer/sharer.php?u=${url}`}; if(links[rede])window.open(links[rede],"_blank");else navigator.clipboard.writeText(location.href);setToast(rede==="Link"?"Link copiado!":"Compartilhamento aberto!");setTimeout(()=>setToast(""),2200)}
 return <main className="site-shell">
  <header className="cabecalho"><button className="marca" onClick={()=>{setPagina("home");setCategoria("Todas")}} aria-label="Ir para o início"><img src="/logo.png" alt="MOVE.ON"/></button><nav className={menu?"nav aberta":"nav"}><button onClick={()=>setPagina("home")}>Início</button><button onClick={()=>{setPagina("home");setTimeout(()=>document.querySelector("#publicacoes")?.scrollIntoView(),20)}}>Publicações</button><button onClick={()=>setCategoria("Tecnologia")}>Tecnologia</button><button onClick={()=>setPagina("admin")}>Administração</button></nav><div className="acoes"><button className="icon-btn" onClick={()=>setBusca(!busca)} aria-label="Abrir busca">⌕</button><button className="theme" onClick={()=>setDark(!dark)} aria-label="Alternar tema"><span>{dark?"☾":"☀"}</span></button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button></div></header>
  {busca&&<div className="busca-overlay" role="dialog" aria-modal="true" aria-label="Busca no portal" onMouseDown={e=>{if(e.target===e.currentTarget)setBusca(false)}}><div className="busca-modal"><button className="fechar-busca" onClick={()=>setBusca(false)} aria-label="Fechar busca">×</button><span>BUSCA INTELIGENTE</span><h2>O que você procura?</h2><p>Encontre publicações por título, conteúdo, assunto ou categoria.</p><div className="campo-busca"><span>⌕</span><input id="q" autoFocus value={termo} onChange={e=>setTermo(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){setPagina("home");setBusca(false)}}} placeholder="Digite para buscar…"/><button onClick={()=>{setPagina("home");setBusca(false)}}>Buscar</button></div></div></div>}
  {pagina==="home"&&<>
   <section className="hero"><div className="hero-img" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.82),rgba(0,0,0,.1)),url(${posts[slide].imagem})`}}/><div className="hero-content"><span className="chapeu">EM DESTAQUE</span><h1>{posts[slide].titulo}</h1><p>{posts[slide].resumo}</p><button className="primario" onClick={()=>abrir(posts[slide])}>Ler publicação <b>→</b></button></div><div className="dots">{[0,1,2].map(i=><button key={i} className={i===slide?"ativo":""} onClick={()=>setSlide(i)} aria-label={`Destaque ${i+1}`}/>)}</div></section>
   <section className="conteudo" id="publicacoes"><div className="titulo-secao"><div><span className="eyebrow">CONTEÚDO QUE MOVE</span><h2>Publicações recentes</h2></div><p>Informação clara para acompanhar um mundo em movimento.</p></div>
    <div className="categorias">{categorias.map(c=><button key={c} className={categoria===c?"ativa":""} onClick={()=>setCategoria(c)}>{c}</button>)}</div>
    <div className="grid-posts">{filtrados.map(p=><article className="post-card" key={p.id} onClick={()=>abrir(p)} onKeyDown={e=>e.key==="Enter"&&abrir(p)} tabIndex={0}><div className="card-img"><img src={p.imagem} alt=""/><div className="card-tags">{categoriasDoPost(p).map(c=><button key={c} className={categoria===c?"selecionada":""} onClick={e=>{e.stopPropagation();setCategoria(c);setToast(`Categoria ${c} selecionada`)}}>{c}</button>)}</div></div><div className="card-body"><div className="meta"><span>{p.data}</span><span>{p.tempo} de leitura</span></div><h3>{p.titulo}</h3><p>{p.resumo}</p><span className="leia">Leia agora <b>↗</b></span></div></article>)}</div>
    {filtrados.length===0&&<div className="vazio"><b>Nenhuma publicação encontrada.</b><p>Tente buscar por outro termo ou categoria.</p></div>}
    <button className="carregar">Carregar mais publicações <span>↓</span></button>
   </section>
   <section className="newsletter"><span>FIQUE POR DENTRO</span><h2>Conteúdo que chega até você.</h2><p>Uma seleção do que realmente importa, direto no seu e-mail.</p><form onSubmit={e=>{e.preventDefault();setToast("Inscrição realizada!")}}><input aria-label="Seu melhor e-mail" placeholder="Seu melhor e-mail" type="email" required/><button>Quero receber</button></form></section>
  </>}
  {pagina==="artigo"&&artigo&&<article className="artigo"><button className="voltar" onClick={voltar}>← Voltar às publicações</button><header><button className="tag" onClick={()=>{setCategoria(artigo.categoria);voltar()}}>{artigo.categoria}</button><h1>{artigo.titulo}</h1><p>{artigo.resumo}</p><div className="artigo-meta"><span>◷ {artigo.data} — horário de Brasília</span><span>◉ {artigo.tempo} de leitura</span></div></header><img className="capa-artigo" src={artigo.imagem} alt="Imagem de capa da publicação"/><div className="artigo-layout"><aside><b>Compartilhe</b><button onClick={()=>compartilhar("WhatsApp")}>W</button><button onClick={()=>compartilhar("LinkedIn")}>in</button><button onClick={()=>compartilhar("Facebook")}>f</button><button onClick={()=>compartilhar("Link")}>↗</button></aside><div className="texto">{artigo.conteudo.split("\n\n").map((p,i)=>i===1?<blockquote key={i}>{p}</blockquote>:<p key={i}>{p}</p>)}<h2>O próximo passo começa agora</h2><p>Mais do que acompanhar tendências, é preciso compreender o que elas significam para a vida real. Informação de qualidade ajuda a escolher caminhos com mais consciência.</p></div></div></article>}
  {pagina==="admin"&&<PainelAdmin onSair={()=>setPagina("home")} setToast={setToast}/>} 
  <footer><img src="/logo.png" alt="MOVE.ON"/><p>Conteúdo para quem não para de evoluir.</p><div><button>Sobre</button><button>Contato</button><button>Privacidade</button></div><small>© 2026 MOVE.ON. Todos os direitos reservados.</small></footer>{toast&&<div className="toast">✓ {toast}</div>}
 </main>
}

function PainelAdmin({onSair,setToast}:{onSair:()=>void,setToast:(v:string)=>void}){
 const [aba,setAba]=useState("Visão geral");
 const itens=[{n:"Visão geral",i:LayoutDashboard},{n:"Publicações",i:FileText},{n:"Nova publicação",i:SquarePen},{n:"Categorias",i:Tags},{n:"Métricas",i:ChartNoAxesCombined},{n:"Aparência",i:Palette},{n:"Administrador",i:UserCog}];
 return <div className="dash2"><aside className="dash-nav"><div className="dash-brand"><img src="/logo.png" alt="MOVE.ON"/><small>ADMINISTRAÇÃO</small></div><nav>{itens.map(({n,i:Icon})=><button key={n} className={aba===n?"ativo":""} onClick={()=>setAba(n)}><Icon size={21}/><span>{n}</span></button>)}</nav><button className="ver-site" onClick={onSair}><ExternalLink size={20}/><span>Ver portal</span></button></aside><section className="dash-area"><header className="dash-header"><div><small>PAINEL ADMINISTRATIVO</small><h1>{aba}</h1></div><div className="dash-user"><div><b>Adimael</b><span>Administrador</span></div><strong>AM</strong></div></header><div className="dash-conteudo">{aba==="Visão geral"&&<ResumoAdmin setAba={setAba}/>} {aba==="Nova publicação"&&<NovoEditor setToast={setToast}/>} {aba==="Publicações"&&<ListaAdmin setAba={setAba}/>} {aba==="Categorias"&&<CategoriasAdmin setToast={setToast}/>} {aba==="Métricas"&&<MetricasAdmin/>} {aba==="Aparência"&&<ConfiguracaoAdmin tipo="aparencia" setToast={setToast}/>} {aba==="Administrador"&&<ConfiguracaoAdmin tipo="administrador" setToast={setToast}/>}</div></section></div>
}
function ResumoAdmin({setAba}:{setAba:(v:string)=>void}){return <><div className="dash-stats">{[[Eye,"12.840","Acessos no mês","+18%"],[Users,"4.620","Leitores únicos","+12%"],[MousePointerClick,"68%","Engajamento","+6%"],[FileText,"42","Publicações","+4"]].map(([Icon,n,l,d]:any)=><div className="stat2" key={l}><div><Icon size={24}/></div><strong>{n}</strong><span>{l}</span><small><TrendingUp size={14}/>{d} no período</small></div>)}</div><div className="dash-duas-colunas"><div className="dash-card grafico2"><CabecalhoCard rotulo="DESEMPENHO" titulo="Acessos nos últimos 7 dias" acao="8.942 acessos"/><div className="barras2">{[45,67,58,81,72,93,76].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][i]}</small></div>)}</div></div><div className="dash-card atalhos2"><CabecalhoCard rotulo="ACESSO RÁPIDO" titulo="Gerencie seu portal"/>{[[SquarePen,"Nova publicação","Crie um novo conteúdo"],[Tags,"Categorias","Organize os assuntos"],[Palette,"Aparência","Personalize a marca"]].map(([Icon,t,s]:any)=><button key={t} onClick={()=>setAba(t==="Nova publicação"?t:t)}><Icon/><span><b>{t}</b><small>{s}</small></span><ChevronRight/></button>)}</div></div><ListaAdmin compacta setAba={setAba}/></>}
function CabecalhoCard({rotulo,titulo,acao}:{rotulo:string,titulo:string,acao?:string}){return <div className="card-head2"><div><small>{rotulo}</small><h2>{titulo}</h2></div>{acao&&<b>{acao}</b>}</div>}
function ListaAdmin({compacta=false,setAba}:{compacta?:boolean,setAba:(v:string)=>void}){return <div className="dash-card lista2"><CabecalhoCard rotulo="CONTEÚDO" titulo={compacta?"Publicações recentes":"Todas as publicações"}/><div className="lista-tools">{!compacta&&<label><Search size={19}/><input placeholder="Buscar publicação…"/></label>}<button onClick={()=>setAba("Nova publicação")}><Plus size={18}/>Nova publicação</button></div><div className="tabela2">{posts.slice(0,compacta?4:6).map((p,i)=><div className="linha2" key={p.id}><img src={p.imagem} alt=""/><div className="titulo-post2"><b>{p.titulo}</b><span>{categoriasDoPost(p).join(" • ")} · {p.data}</span></div><em className={i===2?"rascunho":"publicado"}>{i===2?"Rascunho":"Publicado"}</em><strong>{["2.481","1.920","—","1.574","983","742"][i]}<small> acessos</small></strong><div className="acoes-linha"><button aria-label="Editar"><Pencil size={17}/></button><button aria-label="Excluir"><Trash2 size={17}/></button></div></div>)}</div></div>}
function NovoEditor({setToast}:{setToast:(v:string)=>void}){const [selecionadas,setSelecionadas]=useState<string[]>(["Tecnologia"]);return <div className="novo-editor"><div className="editor-top"><div><h2>Criar nova publicação</h2><p>Preencha os dados e visualize antes de publicar.</p></div><div><button><Eye size={18}/>Visualizar</button><button onClick={()=>setToast("Rascunho salvo!")}><Save size={18}/>Salvar rascunho</button><button className="salvar2" onClick={()=>setToast("Publicação programada!")}><CalendarClock size={18}/>Publicar</button></div></div><div className="editor-grid2"><div className="dash-card editor-principal"><label>Título<input placeholder="Digite um título claro e atrativo"/></label><label>Resumo<textarea placeholder="Escreva uma introdução breve para o card da publicação" rows={3}/></label><label>Conteúdo</label><div className="toolbar2">{[[Bold,"Negrito"],[Italic,"Itálico"],[List,"Lista"],[Quote,"Citação"],[Code2,"Código"],[ImageIcon,"Imagem"],[Video,"Vídeo"]].map(([Icon,label]:any)=><button key={label} title={label}><Icon size={19}/><span>{label}</span></button>)}</div><div className="editor-vazio" contentEditable suppressContentEditableWarning data-placeholder="Comece a escrever sua publicação aqui…"/><div className="upload2"><ImageIcon size={28}/><b>Adicionar imagens de capa</b><span>Arraste imagens ou clique para selecionar · máximo de 5 MB</span></div></div><aside className="dash-card opcoes-editor"><h3>Configurações</h3><label>Status<select><option>Rascunho</option><option>Publicar agora</option><option>Agendado</option></select></label><fieldset><legend>Categorias</legend>{categorias.slice(1).map(c=><button type="button" key={c} className={selecionadas.includes(c)?"selecionada":""} onClick={()=>setSelecionadas(s=>s.includes(c)?s.filter(x=>x!==c):[...s,c])}>{selecionadas.includes(c)?"✓":"＋"} {c}</button>)}</fieldset><label>Agendar<input type="datetime-local"/></label></aside></div></div>}
function CategoriasAdmin({setToast}:{setToast:(v:string)=>void}){return <div className="dash-card pagina2"><CabecalhoCard rotulo="ORGANIZAÇÃO" titulo="Categorias de conteúdo"/><div className="criar-categoria"><input placeholder="Nome da nova categoria"/><button onClick={()=>setToast("Categoria criada!")}><Plus size={18}/>Criar categoria</button></div><div className="grade-categorias2">{categorias.slice(1).map((c,i)=><div key={c}><span><Tags size={20}/></span><div><b>{c}</b><small>{[12,8,10,7,9,6][i]} publicações</small></div><button><Pencil size={17}/></button><button><Trash2 size={17}/></button></div>)}</div></div>}
function MetricasAdmin(){return <><div className="dash-stats">{[[Eye,"1.284","Hoje","+8%"],[Eye,"12.840","Este mês","+18%"],[Users,"4.620","Leitores únicos","+12%"],[MousePointerClick,"68%","Engajamento","+6%"]].map(([Icon,n,l,d]:any)=><div className="stat2" key={l}><div><Icon size={24}/></div><strong>{n}</strong><span>{l}</span><small><TrendingUp size={14}/>{d}</small></div>)}</div><div className="dash-card pagina2"><CabecalhoCard rotulo="DADOS REAIS" titulo="Publicações mais acessadas" acao="Últimos 30 dias"/><p className="nota-metrica">Tráfego administrativo e robôs conhecidos são excluídos da contabilização.</p>{posts.slice(0,5).map((p,i)=><div className="ranking2" key={p.id}><b>0{i+1}</b><span>{p.titulo}</span><strong>{[2481,1920,1574,983,742][i].toLocaleString("pt-BR")} acessos</strong></div>)}</div></>}
function ConfiguracaoAdmin({tipo,setToast}:{tipo:"aparencia"|"administrador";setToast:(v:string)=>void}){const aparencia=tipo==="aparencia";return <div className="dash-card pagina2"><CabecalhoCard rotulo="CONFIGURAÇÕES" titulo={aparencia?"Identidade do portal":"Dados do administrador"}/><div className="config-grid2">{aparencia?<><label>Nome do portal<input defaultValue="MOVE.ON"/></label><label>Descrição<input defaultValue="Conteúdo que move"/></label><label className="upload-config"><ImageIcon/>Alterar logotipo<input type="file" hidden/></label><label className="upload-config"><Settings/>Alterar favicon<input type="file" hidden/></label></>:<><label>Nome<input defaultValue="Adimael"/></label><label>E-mail<input type="email" placeholder="administrador@moveon.com.br"/></label><label>Senha atual<input type="password"/></label><label>Nova senha<input type="password"/></label><label>Confirmar nova senha<input type="password"/></label></>}<button className="salvar2" onClick={()=>setToast("Alterações salvas!")}><Save size={18}/>Salvar alterações</button></div></div>}
function Metric({n,label,delta}:{n:string,label:string,delta:string}){return <div className="metric"><span>↗</span><b>{n}</b><p>{label}</p><small>{delta} no período</small></div>}
function Editor({setToast}:{setToast:(v:string)=>void}){const [selecionadas,setSelecionadas]=useState<string[]>(["Tecnologia"]);const alternar=(c:string)=>setSelecionadas(s=>s.includes(c)?s.filter(x=>x!==c):[...s,c]);return <div className="editor"><div className="form-card"><label>Título da publicação<input placeholder="Digite um título claro e atrativo"/></label><div className="form-row"><fieldset className="seletor-categorias"><legend>Categorias</legend><div>{categorias.slice(1).map(c=><button type="button" key={c} className={selecionadas.includes(c)?"selecionada":""} onClick={()=>alternar(c)}>{selecionadas.includes(c)?"✓ ":"＋ "}{c}</button>)}</div><small>Selecione uma ou mais categorias.</small></fieldset><label>Status<select><option>Rascunho</option><option>Publicar agora</option><option>Agendado</option></select></label></div><label>Resumo<textarea placeholder="Escreva uma breve introdução…" rows={3}/></label><label>Conteúdo</label><div className="toolbar"><button>H1</button><button><b>B</b></button><button><i>I</i></button><button>☷</button><button>“ ”</button><button>&lt;/&gt;</button><button>Imagem</button><button>Vídeo</button></div><div className="content-edit" contentEditable suppressContentEditableWarning>Comece a escrever sua publicação aqui…</div><div className="upload"><b>＋ Adicionar imagens de capa</b><span>JPG, PNG ou WebP · máximo 5 MB cada</span></div><label>Programar publicação<input type="datetime-local"/></label></div><div className="editor-actions"><button>Visualizar</button><button onClick={()=>setToast("Rascunho salvo com segurança!")}>Salvar rascunho</button><button className="primario" onClick={()=>setToast("Publicação programada!")}>Publicar</button></div></div>}
function PaginaAdmin({titulo,setToast}:{titulo:string,setToast:(v:string)=>void}){return <div className="placeholder-admin"><div><span>GESTÃO</span><h2>{titulo}</h2><p>{titulo==="Métricas"?"Dados reais de acesso e engajamento, sem tráfego administrativo ou robôs conhecidos.":"Gerencie esta área do portal com segurança e facilidade."}</p></div><button className="primario" onClick={()=>setToast("Alterações salvas!")}>{titulo==="Publicações"?"＋ Nova publicação":"Salvar alterações"}</button><div className="config-card"><h3>{titulo}</h3><p>Os controles desta seção estão prontos para integração com o banco PostgreSQL e validação segura no servidor.</p><label>Nome ou descrição<input defaultValue={titulo==="Aparência"?"MOVE.ON":""} placeholder="Digite aqui"/></label><label>Configuração<textarea rows={5} placeholder="Adicione informações…"/></label></div></div>}
